name: Publish
on:
  push:
    branches: [develop]
    tags:
    - npm_patch
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: yarn release:patch
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}